version: '3.8'
services:
    database:
        container_name: database
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: symfony_docker
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        ports:
            - '4306:3306'
        volumes:
            - ./mysql:/var/lib/mysql

    php:
        image: php:7.0-fpm
        container_name: php-container

        expose:
            - 9000
        volumes:
            - ./www/html/:/var/www/html/

    nginx:
        image: nginx:latest
        container_name: nginx-container
        ports:
            - 8000

